### PR TITLE
Fixed issue #54 to avoid duplicated prefix name according to aperi2007

### PR DESCRIPTION
**Pull request by jewie**
aperi2007 solved issue#54, this is the pull request.

### CODE REVIEW

**Comment by peter-kutak** [comment]
this patch is working for me

**Comment by jmckenna** [comment]
@jewie we're planning on beginning the TinyOWS 1.2.0 release process on Friday, so if you can re-tackle this pull request with the latest `main` branch (and fix the conflicts) before then, that would be great.

**Comment by jmckenna** [comment]
nudge @aperi2007

**Comment by jmckenna** [comment]
This seems to be fixed earlier through this commit f4345f8

I cannot reproduce now. Closing.

**Pull request closed without merging**
