### PR TITLE
fixed bad conversion of custom types

### PR DESCRIPTION
**Pull request by vmora**
Hi,

For custom types, the elements are cast to string, which is inconvenient. The progress to_json function does the job perfectly.

In this PR, postgres to_json is used to get attributes
as a result, quoting " charaters is not necessary (removed from
buffer_encode_json_str) since it's done by to_json

same remark for the "" enclosing the result in
wfs_geojson_display_results

### CODE REVIEW

**Comment by vpicavet** [comment]
What version of PostgreSQL is required for this code to work ?

**Comment by vmora** [comment]
@vpicavet 9.3 is requiered

**Comment by jmckenna** [comment]
@vmora we're planning on beginning the TinyOWS 1.2.0 release process on Friday, so if you can re-tackle this pull request with the latest `main` branch (and fix the conflicts) before then, that would be great.

**Comment by vmora** [comment]
@jmckenna I completely forgot this PR, fixed the conflicts in the browser but don't have the setup to test the code, plz handle with care (and tests) before merging.

**Comment by jmckenna** [comment]
Thanks for this @vmora     I'd do my best to test your changes locally first, as you said.

**Comment by jmckenna** [comment]
It seems to pass my tests here.  Thanks @vmora !

**Comment by vmora** [comment]
\o/ 

thanks for the tests

**Pull request merged**
